---
# journal config
- name: Create /var/log/journal
  file:
    path: /var/log/journal
    state: directory
    owner: ubuntu
    group: systemd-journal
    mode: 02755

- name: Create /etc/systemd/journald.conf.d
  file:
    path: /etc/systemd/journald.conf.d
    state: directory

- name: Install /etc/systemd/journald.conf.d/journald.conf
  template:
    src: systemd/journald.conf
    dest: /etc/systemd/journald.conf.d/journald.conf
    owner: ubuntu
    group: ubuntu
    mode: 0644
  notify: restart systemd-journald
